### ISSUE TITLE
Add Import Feature

### ISSUE THREAD

**Issue by nramdial** [mulesoft-anypoint/terraform-provider-anypoint#18]
Request to add import of Mule resources into Terraform state.

Cloned from original issue here: https://github.com/mulesoft-consulting/terraform-provider-anypoint/issues/63

**Comment by soufi** [comment]
I think I found a way to add import on existing resources while supporting older versions. 
I will work on the subject soon.

**Comment by soufi** [comment]
The upcoming version v1.6.0 will include import for the existing and new resources.
