### ISSUE TITLE
Feature: add runtime_fabric_environment_association

### ISSUE THREAD

**Issue by drdamour** [mulesoft-anypoint/terraform-provider-anypoint#28]
Would like a reource that's the equivalent of this admin UX
![image](https://github.com/mulesoft-anypoint/terraform-provider-anypoint/assets/1514496/bc1f4078-4bbe-48b5-a0b9-16ea4cd52434)

aware i need to track down the specs and add em...i will follow up when i have a free moment, but wanted to post this feature requests so i have a tracking link

**Comment by artem-kosenko** [comment]
and the RTF instance installation as well will be really helpful. I case you setup multiple instances of RTF for the different business groups on the same or even different K8s clusters.

**Comment by soufi** [comment]
Hello, 
I picked up this subject. Will keep an updated status here. 
If you're interested in helping by testing, it would be much appreciated.

**Comment by soufi** [comment]
Latest code available on branch `features/rtf`. 
This will be part of the next release v1.7.0
