### ISSUE TITLE
Support for Flex Gateway polices

### ISSUE THREAD

**Issue by dfelcey** [mulesoft-anypoint/terraform-provider-anypoint#40]
I like to be able to apply policies to an API associated with a Flex Gateway, like the JWT Validation policy. But this doesn't seem to be supported at the moment

**Comment by soufi** [comment]
Hi @dfelcey, 
Policies are supported, check this out : https://registry.terraform.io/providers/mulesoft-anypoint/anypoint/latest/docs/resources/apim_policy_jwt_validation

A couple policies are supported out the box by the provider. 
For custom policies are other policies that are not explicitly supported, use this: https://registry.terraform.io/providers/mulesoft-anypoint/anypoint/latest/docs/resources/apim_policy_custom

**Comment by dfelcey** [comment]
Thanks a lot and I really appreciate the quick response

Dave


*Dave Felcey, *Principal Solution Engineer

1 St Peter's Square, Manchester M2 3DE

*Mobile: *+447979179464

[image: https://uk.linkedin.com/in/alys-lyndley-27b3b61a]
<https://www.linkedin.com/company/mulesoft/>
<https://twitter.com/mulesoft>   <https://www.facebook.com/MuleSoft>
<https://www.youtube.com/user/mulesoftvids>
