### ISSUE TITLE
Are you open to github sponsorship?

### ISSUE THREAD

**Issue by drdamour** [mulesoft-anypoint/terraform-provider-anypoint#42]
Our company has a vote twice a year on an award to be given to an OSS project we find useful.  The award is $1000 usd and the anypoint terraform provider won the 2024 H1 vote.  We prefer to give the award through github sponsorship program, which you are not currently signed up for. 

Are you able to sign up for it at https://github.com/sponsors/accounts ?  or is there a different platform you would like us to pursue?

congrats on the win.

**Comment by soufi** [comment]
Hi @drdamour, I really appreciate the recognition ! you just made my day :) 
I'm honestly just trying to make this project survive until we can attract a team of volunteers that can take it even further. 
Let me give a thought and get back to you. 

Can you please give me the name of your company ? 

Thank you and it's much appreciated.

**Comment by drdamour** [comment]
@soufi  we sponsor from https://github.com/orgs/simplot/sponsoring?filter=inactive

**Comment by soufi** [comment]
@drdamour. As the only active member of the collective and the only maintainer, you can sponsor me through [Patreon](https://patreon.com/NotASouf?utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink). 
Anything else I'm not able to provide.
