### ISSUE TITLE
terraform init fails, when i create reusable module

### ISSUE THREAD

**Issue by Visha118** [mulesoft-anypoint/terraform-provider-anypoint#51]
I am creating active mq resource.
When I write that resource in main.tf, terraform works fine.
But when I write this resource in reusable module and call that module from main.tf, terraform gives error.
Please help.
Below is the error screenshot -
![image](https://github.com/user-attachments/assets/bb247e48-c7b5-43e3-859c-23e378908280)

**Comment by soufi** [comment]
This is not a bug. This has to do with how you include the provider in your terraform script. 
The anypoint provider is not under hashicorp org, therefore your error is normal. 

please look at the documentation for how to use the provider.
