### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by AgentGoldPaw** [mulesoft-anypoint/terraform-provider-anypoint#6]
Is there any plans to expand this module to account for private spaces or anything related to the latest updates to the platform?

**Comment by soufi** [comment]
Hi @RedMunroe, 
I've been thinking on taking on the Cloudhub 2.0 features and integrate them here. 
Only problem is that I am the only maintainer of this project and I'm trying to keep it alive on top of my other projects. 

I can add some to the todo list if you can list the features your organization is interested in.  

There's a discord server also (https://discord.gg/RmbsuMV8), I'm trying to gather as many people as possible that are interested in this project

**Comment by soufi** [comment]
We have a framework that will allow you to deliver the resources quite easily, join the discord and we can schedule calls where I can help you out understand how it works.

**Comment by soufi** [comment]
there's a permanent link on the welcome page of this org : https://github.com/mulesoft-anypoint

**Comment by TomChapple** [comment]
Do you think that extending that CloudHub 2.0 functionality even further into managing Deployments would be suitable for this provider? I know that [the Kubernetes provider supports defining Deployments as resources](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment) so I imagine this would achieve a similar goal.

**Comment by soufi** [comment]
I don't think a lot of people will use it for this purpose, but It could be a way of managing deployments. 
Also, the artifacts are usually stored somewhere else, you'll have to get the artifact before executing the deployment.

I'm thinking about the next scope we're going to release. Cloudhub is definitely one of them.
