### ISSUE TITLE
Unable to add client certificate to a Load Balancer

### ISSUE THREAD

**Issue by ccortinhas-pmi** [mulesoft-anypoint/terraform-provider-anypoint#9]
Using provider v1.5.2 we are deploying multiple DLBs with certificates. However we noticed that it is not possible to set a Client Certificate, for example of a trusted CA to verify client certificates. 

A close case to ours is explained [here](https://help.mulesoft.com/s/article/How-to-handle-mixed-client-authentication-configuration-one-way-two-way-ssl-in-Dedicated-Load-Balancers).

Notice the second screen in particular and the client certificate:
![image](https://github.com/mulesoft-anypoint/terraform-provider-anypoint/assets/83591746/3929996d-0e43-404f-b06a-4fea80c5a7b7)

We had success in setting the SSL/TLS certificate via terraform, but we also need to apply a client certificate, and it seems that anypoint provider v1.5.2 didn't support that yet.

Can you implement this feature please? It's one of the few mandatory manual steps that's stopping us from fully automating our Mulesoft infrastructure.

**Comment by soufi** [comment]
Hi @ccortinhas-pmi, 
I'm trying to work on your case, but I can't the same page as yours, as I have the following: 

<img width="966" alt="Screenshot 2023-08-23 at 19 03 52" src="https://github.com/mulesoft-anypoint/terraform-provider-anypoint/assets/3698951/52c4ff8c-71bf-40a3-9605-1b839f8291c0">

do you havae some specific options ?

**Comment by ccortinhas-pmi** [comment]
Hi @soufi ,

It seems that "Client Certificate" was rebranded to "Trusted CA File" on the UI, so you are getting the correct field.

Nonetheless I created a new certificate just to replicate the payload of the PATCH request and is as follows:
```json
[
   {
      "op":"replace",
      "path":"/defaultSslEndpoint",
      "value":1
   },
   {
      "op":"add",
      "path":"/sslEndpoints/0",
      "value":{
         "publicKeyLabel":"domain.pem",
         "publicKey":"",
         "privateKeyLabel":"domain.key",
         "privateKey":"",
         "mappings":[
            {
               "inputUri":"/{app}/",
               "appName":"{app}",
               "appUri":"/",
               "upstreamProtocol":"http"
            }
         ],
         "privateKeyDigest":"",
         "publicKeyDigest":"",
         "publicKeyCN":"domain",
         "publicKeySANs":[
            
         ],
         "clientCertCN":"domain",
         "clientCertDigest":"",
         "revocationList":"",
         "revocationListLabel":null,
         "clientCert":"",
         "clientCertLabel":"label.pem"
      }
   },
   {
      "op":"replace",
      "path":"/sslEndpoints/1/mappings",
      "value":[
        (...)
      ]
   },
   {
      "op":"replace",
      "path":"/doubleStaticIps",
      "value":false
   }
]
```

I hope this helps.

**Comment by soufi** [comment]
hey @ccortinhas-pmi, 

I'm happy to announce that the version v1.5.4 is published with plenty of enhancement for DLB. 

Thank you for using this tool.
